from datetime import date
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.platypus import Table, TableStyle

def _money(n):
    # ASCII only (avoid missing glyph issues)
    return f"{int(round(n)):,} KRW"

def _draw_card(c, x, y, w, h, title=None):
    c.setFillColor(colors.white)
    c.setStrokeColor(colors.Color(0.85, 0.85, 0.85))
    c.roundRect(x, y, w, h, 8, stroke=1, fill=1)
    if title:
        c.setFont("Helvetica-Bold", 10)
        c.setFillColor(colors.HexColor("#333333"))
        c.drawString(x + 10, y + h - 18, title)

def build_payslip_pdf(path: str, payload: dict):
    """
    payload keys:
      month_name, year, employee_name, designation, pay_period, pay_date,
      net_salary (number),
      earnings: list[(label, amount)],
      deductions: list[(label, amount)]
    """
    W, H = A4
    m = 18 * mm
    c = canvas.Canvas(path, pagesize=A4)
    c.setTitle("Payslip")

    # Header
    c.setFillColor(colors.HexColor("#111827"))
    c.setFont("Helvetica-Bold", 20)
    c.drawString(m, H - m - 8, "Payslip")

    c.setFillColor(colors.HexColor("#6B7280"))
    c.setFont("Helvetica", 12)
    c.drawString(m, H - m - 28, f"For the month: {payload['month_name']} {payload['year']}")

    # Cards
    card_gap = 10
    card_h = 90
    card_y = H - m - 28 - 18 - card_h
    card_w = (W - 2 * m - card_gap) / 2

    # Employee card
    x1 = m
    _draw_card(c, x1, card_y, card_w, card_h, "Employee Information")
    c.setFont("Helvetica", 10)
    lines = [
        ("Name", payload["employee_name"]),
        ("Designation", payload["designation"]),
        ("Pay period", payload["pay_period"]),
        ("Pay date", payload["pay_date"]),
    ]
    yy = card_y + card_h - 34
    for k, v in lines:
        c.setFillColor(colors.HexColor("#6B7280"))
        c.drawString(x1 + 10, yy, f"{k}:")
        c.setFillColor(colors.HexColor("#111827"))
        c.drawString(x1 + 90, yy, str(v))
        yy -= 14

    # Net salary card
    x2 = m + card_w + card_gap
    _draw_card(c, x2, card_y, card_w, card_h, "Net Salary")
    c.setFont("Helvetica-Bold", 22)
    c.setFillColor(colors.HexColor("#6FDA60"))
    c.drawString(x2 + 10, card_y + 28, _money(payload["net_salary"]))
    c.setFont("Helvetica", 9)
    c.setFillColor(colors.HexColor("#6FDA60"))
    c.drawString(x2 + 10, card_y + 14, "Net amount to be paid")

    # Earnings/Deductions table
    table_top = card_y - 18
    table_x = m
    table_w = W - 2 * m

    rows = max(len(payload["earnings"]), len(payload["deductions"]))
    body = []
    for i in range(rows):
        e = payload["earnings"][i] if i < len(payload["earnings"]) else ("", "")
        d = payload["deductions"][i] if i < len(payload["deductions"]) else ("", "")
        body.append([
            e[0], _money(e[1]) if e[0] else "",
            d[0], _money(d[1]) if d[0] else ""
        ])

    header = ["Earnings", "Amount", "Deductions", "Amount"]
    tdata = [header] + body + [["", "", "", ""]]

    gross = sum(v for _, v in payload["earnings"])
    total_ded = sum(v for _, v in payload["deductions"])
    tdata.append(["Gross Earnings", _money(gross), "Total Deductions", _money(total_ded)])

    col_w = [table_w * 0.30, table_w * 0.20, table_w * 0.30, table_w * 0.20]
    t = Table(tdata, colWidths=col_w)

    t.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#111827")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),

        ("ALIGN", (1,1), (1,-1), "RIGHT"),
        ("ALIGN", (3,1), (3,-1), "RIGHT"),

        ("TEXTCOLOR", (3,1), (3,-2), colors.HexColor("#B91C1C")),
        ("FONTNAME", (3,1), (3,-2), "Helvetica-Bold"),

        ("TEXTCOLOR", (2,1), (2,-2), colors.HexColor("#6B7280")),

        ("GRID", (0,0), (-1,-1), 0.25, colors.HexColor("#D1D5DB")),
        ("ROWBACKGROUNDS", (0,1), (-1,-3), [colors.white, colors.HexColor("#F9FAFB")]),

        ("BACKGROUND", (0,-1), (-1,-1), colors.HexColor("#F3F4F6")),
        ("TEXTCOLOR", (3,-1), (3,-1), colors.HexColor("#991B1B")),
        ("FONTNAME", (0,-1), (-1,-1), "Helvetica-Bold"),
    ]))


    tw, th = t.wrapOn(c, table_w, 0)
    t.drawOn(c, table_x, table_top - th)

    # Footer note
    c.setFont("Helvetica", 8)
    c.setFillColor(colors.HexColor("#6B7280"))
    c.drawString(m, 12 * mm, "Generated by Expense Tracker. Values are based on recorded logs and settings.")
    c.showPage()
    c.save()
