"""add budgets_type for type-scoped budgets

Revision ID: 36919636436a
Revises: 75158a1e5b83
Create Date: 2025-10-11 14:22:19.501002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36919636436a'
down_revision = '75158a1e5b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('txn_type', sa.Enum('income', 'expense', 'transfer_domestic', 'transfer_international', 'refund', 'fee', 'adjustment', name='txn_type_enum'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year', 'month', 'txn_type', name='uq_btype_user_year_month_type'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('budgets_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_type_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgets_type_user_id'))

    op.drop_table('budgets_type')
    # ### end Alembic commands ###
