"""add paid leave type to work logs

Revision ID: 71541f926c0c
Revises: d784028f5623
Create Date: 2026-05-28 20:56:20.339840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71541f926c0c'
down_revision = 'd784028f5623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lotto_draw_number', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_draw_position'), type_='unique')

    with op.batch_alter_table('lotto_pick_set', schema=None) as batch_op:
        batch_op.create_index('idx_lotto_pick_set_game_round', ['game_id', 'generated_for_round_no'], unique=False)

    with op.batch_alter_table('work_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leave_type', sa.String(length=20), server_default='unpaid', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_logs', schema=None) as batch_op:
        batch_op.drop_column('leave_type')

    with op.batch_alter_table('lotto_pick_set', schema=None) as batch_op:
        batch_op.drop_index('idx_lotto_pick_set_game_round')

    with op.batch_alter_table('lotto_draw_number', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_draw_position'), ['draw_id', 'position'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
