"""Added debt  model

Revision ID: 75158a1e5b83
Revises: 735214de64b3
Create Date: 2025-10-04 14:17:34.189748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75158a1e5b83'
down_revision = '735214de64b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debt_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('owe', 'lend', name='debt_direction_enum', native_enum=False), nullable=False),
    sa.Column('currency', sa.Enum('KRW', 'BDT', name='currency_enum', native_enum=False), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('original_principal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('outstanding_principal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('debt_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_debt_items_user_id'), ['user_id'], unique=False)

    op.create_table('debt_txns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('principal_portion', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('interest_portion', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('fee_portion', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['debt_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('debt_txns', schema=None) as batch_op:
        batch_op.create_index('ix_debt_txns_user_date', ['user_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_debt_txns_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt_txns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debt_txns_user_id'))
        batch_op.drop_index('ix_debt_txns_user_date')

    op.drop_table('debt_txns')
    with op.batch_alter_table('debt_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debt_items_user_id'))

    op.drop_table('debt_items')
    # ### end Alembic commands ###
