"""add salary tracker tables

Revision ID: 75b55d6fb9ae
Revises: 36919636436a
Create Date: 2026-01-01 00:20:03.320217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b55d6fb9ae'
down_revision = '36919636436a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'holiday_date', name='uq_holiday_user_date')
    )
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holidays_holiday_date'), ['holiday_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_holidays_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_holidays_year'), ['year'], unique=False)

    op.create_table('salary_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('salary_adjustments', schema=None) as batch_op:
        batch_op.create_index('ix_salary_adjust_user_month', ['user_id', 'year', 'month'], unique=False)
        batch_op.create_index(batch_op.f('ix_salary_adjustments_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_salary_adjustments_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_salary_adjustments_year'), ['year'], unique=False)

    op.create_table('salary_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hours_per_day', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('overtime_multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('default_lunch_minutes', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('salary_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salary_settings_user_id'), ['user_id'], unique=False)

    op.create_table('work_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('in_time', sa.Time(), nullable=True),
    sa.Column('out_time', sa.Time(), nullable=True),
    sa.Column('lunch_minutes', sa.Integer(), nullable=False),
    sa.Column('is_full_day_leave', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('worked_minutes', sa.Integer(), nullable=False),
    sa.Column('regular_minutes', sa.Integer(), nullable=False),
    sa.Column('overtime_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'work_date', name='uq_worklog_user_date')
    )
    with op.batch_alter_table('work_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_logs_work_date'), ['work_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_logs_work_date'))
        batch_op.drop_index(batch_op.f('ix_work_logs_user_id'))

    op.drop_table('work_logs')
    with op.batch_alter_table('salary_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salary_settings_user_id'))

    op.drop_table('salary_settings')
    with op.batch_alter_table('salary_adjustments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salary_adjustments_year'))
        batch_op.drop_index(batch_op.f('ix_salary_adjustments_user_id'))
        batch_op.drop_index(batch_op.f('ix_salary_adjustments_month'))
        batch_op.drop_index('ix_salary_adjust_user_month')

    op.drop_table('salary_adjustments')
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holidays_year'))
        batch_op.drop_index(batch_op.f('ix_holidays_user_id'))
        batch_op.drop_index(batch_op.f('ix_holidays_holiday_date'))

    op.drop_table('holidays')
    # ### end Alembic commands ###
