"""lotto tables

Revision ID: d784028f5623
Revises: 75b55d6fb9ae
Create Date: 2026-01-04 23:00:51.604491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd784028f5623'
down_revision = '75b55d6fb9ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotto_game',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('numbers_per_draw', sa.SmallInteger(), nullable=False),
    sa.Column('min_num', sa.SmallInteger(), nullable=False),
    sa.Column('max_num', sa.SmallInteger(), nullable=False),
    sa.Column('has_bonus', sa.Boolean(), nullable=False),
    sa.Column('low_high_split', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lotto_draw',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('round_no', sa.Integer(), nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=False),
    sa.Column('bonus', sa.SmallInteger(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['lotto_game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'round_no', name='uq_lotto_draw_game_round')
    )
    with op.batch_alter_table('lotto_draw', schema=None) as batch_op:
        batch_op.create_index('idx_lotto_draw_game_date', ['game_id', 'draw_date'], unique=False)
        batch_op.create_index('idx_lotto_draw_game_round', ['game_id', 'round_no'], unique=False)

    op.create_table('lotto_pick_set',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('generated_for_round_no', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rules_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_round_no', sa.Integer(), nullable=True),
    sa.Column('matched_main_count', sa.SmallInteger(), nullable=True),
    sa.Column('matched_bonus', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['lotto_game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lotto_pick_set', schema=None) as batch_op:
        batch_op.create_index('idx_lotto_pick_set_game_generated', ['game_id', 'generated_at'], unique=False)

    op.create_table('lotto_draw_number',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('draw_id', sa.BigInteger(), nullable=False),
    sa.Column('num', sa.SmallInteger(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=True),
    sa.Column('is_bonus', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['draw_id'], ['lotto_draw.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draw_id', 'num', name='uq_draw_num'),
    sa.UniqueConstraint('draw_id', 'position', name='uq_draw_position')
    )
    with op.batch_alter_table('lotto_draw_number', schema=None) as batch_op:
        batch_op.create_index('idx_lotto_draw_number_draw', ['draw_id'], unique=False)
        batch_op.create_index('idx_lotto_draw_number_num', ['num'], unique=False)
        batch_op.create_index('idx_lotto_draw_number_num_draw', ['num', 'draw_id'], unique=False)

    op.create_table('lotto_draw_stats',
    sa.Column('draw_id', sa.BigInteger(), nullable=False),
    sa.Column('sum_total', sa.Integer(), nullable=False),
    sa.Column('odd_count', sa.SmallInteger(), nullable=False),
    sa.Column('even_count', sa.SmallInteger(), nullable=False),
    sa.Column('low_count', sa.SmallInteger(), nullable=False),
    sa.Column('high_count', sa.SmallInteger(), nullable=False),
    sa.Column('range_span', sa.SmallInteger(), nullable=False),
    sa.Column('avg_gap', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('min_gap', sa.SmallInteger(), nullable=False),
    sa.Column('max_gap', sa.SmallInteger(), nullable=False),
    sa.Column('consecutive_pairs_count', sa.SmallInteger(), nullable=False),
    sa.Column('max_consecutive_run', sa.SmallInteger(), nullable=False),
    sa.Column('repeat_from_prev1', sa.SmallInteger(), nullable=True),
    sa.Column('repeat_from_prev2', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draw_id'], ['lotto_draw.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('draw_id')
    )
    with op.batch_alter_table('lotto_draw_stats', schema=None) as batch_op:
        batch_op.create_index('idx_lotto_draw_stats_sum', ['sum_total'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lotto_draw_stats', schema=None) as batch_op:
        batch_op.drop_index('idx_lotto_draw_stats_sum')

    op.drop_table('lotto_draw_stats')
    with op.batch_alter_table('lotto_draw_number', schema=None) as batch_op:
        batch_op.drop_index('idx_lotto_draw_number_num_draw')
        batch_op.drop_index('idx_lotto_draw_number_num')
        batch_op.drop_index('idx_lotto_draw_number_draw')

    op.drop_table('lotto_draw_number')
    with op.batch_alter_table('lotto_pick_set', schema=None) as batch_op:
        batch_op.drop_index('idx_lotto_pick_set_game_generated')

    op.drop_table('lotto_pick_set')
    with op.batch_alter_table('lotto_draw', schema=None) as batch_op:
        batch_op.drop_index('idx_lotto_draw_game_round')
        batch_op.drop_index('idx_lotto_draw_game_date')

    op.drop_table('lotto_draw')
    op.drop_table('lotto_game')
    # ### end Alembic commands ###
